"""create_user_model

Revision ID: b3fc08b3b65a
Revises:
Create Date: 2023-03-29 21:38:02.148044

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b3fc08b3b65a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column("mobile_number", sa.String(length=128), nullable=False),
        sa.Column("postal_address", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_model_email"), "user_model", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_model_email"), table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###
