"""They didnt change active

Revision ID: 765ca0a02a73
Revises: 58abc215b1b8
Create Date: 2023-03-31 15:11:03.109813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "765ca0a02a73"
down_revision = "58abc215b1b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_model",
        "active_plan_id",
        existing_type=mysql.VARCHAR(length=36),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_model",
        "active_plan_id",
        existing_type=mysql.VARCHAR(length=36),
        nullable=False,
    )
    # ### end Alembic commands ###
